datagrid:
    ktpl_akeneo_category_trash-grid:
        options:
            entityHint: category
            locale_parameter: localeCode
            manageFilters: false
        source:
            acl_resource: ktpl_akeneo_trash_category_index
            type: ktpl_akeneo_trash_datasource_category
        columns:
            label:
                label: Label
                frontend_type: label
            parent_label:
                label:     Parent
                frontend_type: label
            root_label:
                label:     Root Tree
                frontend_type: label
        properties:
            id: ~
            delete_link:
                type: url
                route: ktpl_akeneo_trash_category_rest_remove
                params:
                    - id
            restore_link:
                type: url
                route: ktpl_akeneo_trash_rest_restore
                params:
                    - id
        actions:
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:  delete-category-trash
                label: pim_common.delete
                link:  delete_link
                acl_resource: ktpl_akeneo_trash_remove_category
            restore:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--restore
                type:  delete-restore-category-trash
                label: pim_datagrid.actions.restore_trash
                link:  restore_link
                acl_resource: ktpl_akeneo_trash_restore_trash
        sorters:
            columns:
                label:
                    data_name: translation.label
            default:
                label: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                code:
                    type:      string
                    label:     pim_common.code
                    data_name: c.code
                label:
                    type:      search
                    label:     Label
                    data_name: translation.label
        mass_actions:
            delete_categories_from_trash:
                type: akeneo_trash_category_mass_delete
                label: pim_common.delete
                entity_name: category
                acl_resource: ktpl_akeneo_trash_remove_product
                handler: trash_mass_delete
                className: 'AknButton AknButton--important AknButtonList-item'
                messages:
                    confirm_title: pim_common.confirm_deletion
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: pim_common.ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection

            restore_categories_from_trash:
                type: akeneo_trash_category_mass_restore
                label: pim_datagrid.actions.restore_trash
                entity_name: category
                acl_resource: ktpl_akeneo_trash_restore_trash
                handler: trash_mass_restore
                className: 'AknButton AknButton--action AknButtonList-item'
                messages:
                    confirm_title: ktpl.akeneo_trash.entity.confirm_restore
                    confirm_content: ktpl.akeneo_trash.entity.confirm_content
                    confirm_ok: pim_common.ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
