datagrid:
    ktpl_akeneo_product_trash-grid:
        options:
            entityHint: product
            filtersAsColumn: true
            displayTypes:
                default:
                    label: pim_datagrid.display_selector.list
                gallery:
                    label: pim_datagrid.display_selector.gallery
                    rowView: oro/datagrid/product-row
                    manageColumns: false
        source:
            acl_resource:      ktpl_akeneo_trash_product_index
            type:              pim_datasource_product
            entity:            '%pim_catalog.entity.product.class%'
        columns:
            identifier:
                label: ID
                data_name:     identifier
                type:          field
            image:
                label:         Image
                data_name:     image
                frontend_type: product-and-product-model-image
            label:
                label:         Label
                data_name:     label
                type:          field
                frontend_type: product-and-product-model-label
            family:
                label:         Family
                data_name:     family
                type:          field
            enabled:
                label:         Status
                frontend_type: enabled
            completeness:
                label:         Complete
                frontend_type: completeness
            created:
                label:         Created At
                type:          field
            updated:
                label:         Updated At
                type:          field
            complete_variant_products:
                label:         Variant products
                data_name:     complete_variant_product
                frontend_type: complete-variant-product
        other_columns:
            groups:
                label:         Groups
                data_name:     groups
                type:          field
            parent:
                label: Parent
                data_name: parent
                type: field
        properties:
            id:
                type:          field
                data_name:     search_id
            label:
                type:          field
                data_name:     label
            image:
                data_name:     image
                frontend_type: product-and-product-model-image
            identifier:
                type:          field
                data_name:     identifier
            completeness:
                type:          field
                frontend_type: completeness
            complete_variant_products:
                type:          field
                data_name:     complete_variant_product
                frontend_type: complete-variant-product
            document_type: ~
            technical_id: ~
            delete_link:
                type: url
                route: ktpl_akeneo_trash_product_rest_remove
                params:
                    - id
            restore_link:
                type: url
                route: ktpl_akeneo_trash_rest_restore
                params:
                    - id
        actions:
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:  delete-product-trash
                label: pim_datagrid.actions.delete_product
                link:  delete_link
                acl_resource: ktpl_akeneo_trash_remove_product
            restore:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--restore
                type:  delete-restore-product-trash
                label: pim_datagrid.actions.restore_trash
                link:  restore_link
                acl_resource: ktpl_akeneo_trash_restore_trash
        mass_actions:
            delete_products_product_models_from_trash:
                type: akeneo_trash_mass_delete
                label: pim_common.delete
                entity_name: product
                acl_resource: ktpl_akeneo_trash_remove_product
                handler: product_akeneo_trash_mass_delete
                className: 'AknButton AknButton--important AknButtonList-item'
                messages:
                    confirm_title: pim_common.confirm_deletion
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: pim_common.ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection

            restore_products_product_models_from_trash:
                type: akeneo_trash_mass_restore
                label: pim_datagrid.actions.restore_trash
                entity_name: product
                acl_resource: ktpl_akeneo_trash_restore_trash
                handler: product_akeneo_trash_mass_restore
                className: 'AknButton AknButton--action AknButtonList-item'
                messages:
                    confirm_title: ktpl.akeneo_trash.entity.confirm_restore
                    confirm_content: ktpl.akeneo_trash.entity.confirm_content
                    confirm_ok: pim_common.ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
        sorters:
            columns:
                identifier:
                    data_name: identifier
                    sorter: product_field
                family:
                    data_name: familyLabel
                    sorter:    product_family
                enabled:
                    data_name: enabled
                    sorter:    product_field
                completeness:
                    data_name: ratio
                    sorter:    product_completeness
                created:
                    data_name: created
                    sorter:    product_field
                updated:
                    data_name: updated
                    sorter:    product_field
            default:
                updated: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        filters:
            columns:
                family:
                    type:      product_family
                    label:     Family
                    data_name: family
                    options:
                        field_options:
                            multiple: true
                            attr:
                                empty_choice: true
                groups:
                    type:      product_groups
                    label:     Groups
                    data_name: groups
                    options:
                        field_options:
                            multiple: true
                enabled:
                    type:      product_enabled
                    ftype:     choice
                    label:     Status
                    data_name: enabled
                    options:
                        field_options:
                            choices:
                                Enabled: 1
                                Disabled: 0
                completeness:
                    type:      product_and_product_model_completeness
                    label:     Complete
                    data_name: ratio
                created:
                    type:      product_date
                    ftype:     date
                    data_name: created
                    label:     Created At
                updated:
                    type:      product_date
                    ftype:     date
                    data_name: updated
                    label:     Updated At
                label_or_identifier:
                    type: label_or_identifier
                    label: Label or identifier
                    data_name: label_or_identifier
                parent:
                    label:         Parent
                    data_name:     parent
                    type:          product_value_string
                    ftype:         parent
                    options:
                        field_options:
                            attr:
                                choice_list: true