extensions:
    pim-ktpl_akeneo_trash_family_variant-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    pim-ktpl_akeneo_trash_family_variant-index-grid-container:
        module: pim/common/simple-view
        parent: pim-ktpl_akeneo_trash_family_variant-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pim-ktpl_akeneo_trash_family_variant-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-ktpl_akeneo_trash_family_variant-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-ktpl_akeneo_trash_family_variant-index-grid-title:
        module: pim/common/grid-title
        parent: pim-ktpl_akeneo_trash_family_variant-index
        targetZone: title
        config:
            title: pim_enrich.entity.family_variant.page_title.index

    pim-ktpl_akeneo_trash_family_variant-index-grid-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-ktpl_akeneo_trash_family_variant-index
        targetZone: breadcrumbs
        config:
            tab: ktpl-akeneo_trash-menu-trash
            item: ktpl-akeneo_trash-menu-family-variant

    pim-ktpl_akeneo_trash_family_variant-index-mass-actions:
        module: pim/grid/mass-actions
        parent: pim-ktpl_akeneo_trash_family_variant-index
        targetZone: bottom-panel
        config:
            label: pim_datagrid.mass_action.selected.family_variant

    pim-ktpl_akeneo_trash_family_variant-index-actions-panel:
        module: oro/datagrid/actions-panel
        parent: pim-ktpl_akeneo_trash_family_variant-index-mass-actions
        targetZone: actions-panel

    pim-ktpl_akeneo_trash_family_variant-index-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-ktpl_akeneo_trash_family_variant-index-grid-container
        targetZone: filters

    pim-ktpl_akeneo_trash_family_variant-index-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-ktpl_akeneo_trash_family_variant-index-grid-container
        targetZone: filters
        
    pim-ktpl_akeneo_trash_family_variant-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-ktpl_akeneo_trash_family_variant-index-grid-container
        targetZone: toolbar
        config:
            gridName: ktpl_akeneo_family_variant_trash-grid

    pim-ktpl_akeneo_trash_family_variant-index-grid:
        module: pim/form/common/index/grid
        parent: pim-ktpl_akeneo_trash_family_variant-index-grid-container
        position: 1000
        config:
            alias: ktpl_akeneo_family_variant_trash-grid