services:
    ktpl.akeneo_trash.extension.action.type.delete_product_trash:
        public: true
        class: '%pim_enrich.extension.action.type.delete_product.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-product-trash }

    ktpl.akeneo_trash.extension.action.type.restore_product_trash:
        public: true
        class: '%pim_enrich.extension.action.type.delete_product.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-restore-product-trash }

    ktpl.akeneo_trash.extension.action.type.delete_category_trash:
        public: true
        class: '%oro_datagrid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-category-trash }

    ktpl.akeneo_trash.extension.action.type.restore_category_trash:
        public: true
        class: '%oro_datagrid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-restore-category-trash }
    
    ktpl.akeneo_trash.extension.action.type.delete_family_trash:
        public: true
        class: '%oro_datagrid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-family-trash }

    ktpl.akeneo_trash.extension.action.type.restore_family_trash:
        public: true
        class: '%oro_datagrid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-restore-family-trash }

    ktpl.akeneo_trash.extension.action.type.delete_family_variant_trash:
        public: true
        class: '%oro_datagrid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-family-variant-trash }

    ktpl.akeneo_trash.extension.action.type.restore_family_variant_trash:
        public: true
        class: '%oro_datagrid.extension.action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete-restore-family-variant-trash }