services:
    ktpl.akeneo_trash.repository.akeneo_trash:
      class: 'KTPL\AkeneoTrashBundle\Repository\AkeneoTrashRepository'
      factory: 'doctrine.orm.default_entity_manager:getRepository'
      arguments: ['KTPL\AkeneoTrashBundle\Entity\AkeneoTrash']
      tags:
          - { name: 'pim_repository' }

    ktpl.akeneo_trash.repository.category:
        class: 'KTPL\AkeneoTrashBundle\Repository\InternalApi\CategoryRepository'
        public: true
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'

    ktpl.akeneo_trash.repository.family_variant:
        class: 'KTPL\AkeneoTrashBundle\Doctrine\ORM\Repository\InternalApi\FamilyVariantRepository'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.family_variant.class%'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'

    pim_catalog.repository.category:
        class: 'KTPL\AkeneoTrashBundle\Doctrine\ORM\Repository\CategoryRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.category.class%']
        calls:
            - method: setAkeneoTrashManager
              arguments:
                - '@ktpl.akeneo_trash.manager.akeneo_trash'
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.product_category:
        class:  'KTPL\AkeneoTrashBundle\Doctrine\ORM\Repository\ProductCategoryRepository'
        parent: akeneo_classification.repository.abstract_item_category
        arguments:
            - '@pim_catalog.object_manager.product'
            - '%pim_catalog.entity.product.class%'
            - '%pim_catalog.entity.category.class%'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'

    pim_catalog.repository.product_model_category:
        class:  'KTPL\AkeneoTrashBundle\Doctrine\ORM\Repository\ProductModelCategoryRepository'
        parent: akeneo_classification.repository.abstract_item_category
        arguments:
            - '@pim_catalog.object_manager.product'
            - '%pim_catalog.entity.product_model.class%'
            - '%pim_catalog.entity.category.class%'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'

    pim_enrich.repository.family.search:
        class: 'KTPL\AkeneoTrashBundle\Doctrine\ORM\Repository\InternalApi\FamilySearchableRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.family.class%'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'

    pim_enrich.repository.family_variant.search:
        class: 'KTPL\AkeneoTrashBundle\Doctrine\ORM\Repository\InternalApi\FamilyVariantSearchableRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.family_variant.class%'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'