services:
    ktpl.akeneo_trash.factory.mass_edit_notification:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Factory\MassEditNotificationFactory'
        arguments:
            - ['akeneo_trash_mass_delete', 'mass_restore']
            - '%pim_notification.entity.notification.class%'
        tags:
            - { name: pim_notification.factory.notification }
    